blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog/

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /shop/
    
app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
default:
    path: /
    defaults: 
        _controller: "AppBundle:Default:index"
        
news_main:
    path: /news
    defaults: 
        _controller: "AppBundle:Default:news"
    
news_details:
    path: /news/view/{name}
    defaults: 
        _controller: "AppBundle:Default:news"
        
news_page:
    path: /news/page/{page}
    defaults: 
        _controller: "AppBundle:Default:news"
        page: 1
    requirements:
        page: \d+
        
news_ordered:
    path: /news/page/{page}/sort/{sort}/order/{order}
    defaults: 
        _controller: "AppBundle:Default:news"
    requirements:
        page: \d+
        order: asc|desc
    
news_main_lang:
    path: /{lang}/news
    defaults: 
        _controller: "AppBundle:Default:news"
        lang: ua
    requirements:
        lang: ua|en|ru
        
welcome:
    path: /welcome
    defaults: 
        _controller: "AppBundle:Lesson:welcome"
        
save:
    path: /save
    defaults: { _controller: "AppBundle:Data:save" }
    
get_product:
    path:     /get_product
    defaults: { _controller: AppBundle:Data:get }    
    
register:
    path:     /register
    defaults: { _controller: AppBundle:User:register }  
register_success:
    path:     /register_success
    defaults: { _controller: AppBundle:User:registerSuccess }  
admin:
    path:     /admin
    defaults: { _controller: AppBundle:User:admin }
    
profile:
    path:     /profile
    defaults: { _controller: AppBundle:User:profile } 
    
login:
    path:     /login
    defaults: { _controller: AppBundle:User:login } 