app:
    resource: '@AppBundle/Controller/'
    type: annotation

blog_routing:
    path: /blog/{page}
    defaults: {_controller: "AppBundle:Default:blog", page: 0}
    
news_main:
    path: /news
    defaults: {_controller: "AppBundle:Default:news"}