<?php

namespace BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getAll() {
        // still in dev 
        $em = $this->getDoctrine()->getManager();
        $query = $em->createQuery("
            SELECT p, count(c.id)
            FROM BlogBundle:Post 
            JOIN p.comments c
            GROUP BY p.id");
            
        return $query->getResult();
    }
    
}
