blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_post_add:
    path:   /post/add/{id}
    defaults: 
        _controller: BlogBundle:Default:add
        id: 0
    
blog_post:
    path:   /post/{id}
    defaults: { _controller: BlogBundle:Default:details }
    
