BlogBundle\Entity\User:
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~
            
BlogBundle\Entity\Post:
    properties:
        title:
            - NotBlank: ~
        content:
            - NotBlank: ~