
index:
    path:     /
    defaults: { _controller: AppBundle:Blog:index }

view:
    path:     /view/{id}
    requirements:
        id: \d+
    defaults: { _controller: AppBundle:Blog:view }

add:
    path:     /add
    defaults: { _controller: AppBundle:Blog:add }

save:
    path:     /save
    defaults: { _controller: AppBundle:Data:save }
