
index:
    path:     /index
    defaults: { _controller: AppBundle:BlogController:index }

view:
    path:     /view
    defaults: { _controller: AppBundle:BlogController:view }

add:
    path:     /add
    defaults: { _controller: AppBundle:BlogController:add }
