
index:
    path:     /
    defaults: { _controller: AppBundle:Blog:index }

view:
    path:     /view
    defaults: { _controller: AppBundle:Blog:view }

add:
    path:     /add
    defaults: { _controller: AppBundle:Blog:add }
