shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }

shop_category:
    path: /{name}
    defaults: { _controller: ShopBundle:Default:category }
    
shop_item:
    path: /{category_name}/{id}
    defaults: { _controller: ShopBundle:Default:item }