BlogBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
        date:
            type: datetime
    lifecycleCallbacks: {  }
