BlogBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        date:
            type: datetime
    lifecycleCallbacks: {  }
    
    manyToOne:
        category:
            targetEntity: Category
        user:
            targetEntity: User
            
    oneToMany:
        comments:
            targetEntity: Comment
            mappedBy: post

    manyToMany:
        tags:
            targetEntity: Tag